### ISSUE TITLE
Could not get container for s3

### ISSUE THREAD

**Issue by mangis-emc** [emccode/mosaicme#5]
Hi, I tried to deploy the app and use Amazon S3 buckets to play with it. It says that it can't find a container for S3... Do I need ECS service also with Amazon S3? Or am I missing something? It's my first time trying a Docker app.

**Comment by kacole2** [comment]
@adrianmo @pbutlerm ??

**Comment by adrianmo** [comment]
@mangis-emc thanks for the warning. The error you are seeing is due to a test setup we did with a S3 service running as a container. I have already removed the `--link s3:s3` from the deployment guide and you should be good to go. I'm closing this issue but let us know if you have any more problems deploying it. Thanks.
